### ISSUE TITLE
Integration of Bitcoin assets

### ISSUE THREAD

**Issue by hieudd** [Koniverse/Playnation#57]
Bitcoin is the most valuable ecosystem in the blockchain industry and is making many improvements to onboard end users and retail users. 

Playnation needs to support popular assets across the Bitcoin ecosystem to help onboard new users quickly and attract users from Bitcoin to Polkadot through native bridge asset:

- [ ] SWAP BTC <=> DOT

## Types of assets that need to be integrated:

- [ ] BTC Native
- [ ] Ordinal Collections
- [ ] BRC-20
- [ ] Rune 

## Tasks that need to be done

- [ ] Research the data structure of asset types on BTC
- [ ] Research and Implement Keyring to sign transactions and generate wallet addresses across the BTC ecosystem
   - [ ] BTC Keyring
   - [ ] BTC Address
- [ ] Research on new Bitcoin asset classes
   - [ ] Ordinals
   - [ ] BRC-20
   - [ ] Rune
- [ ] Research and deploy data infrastructure systems for Bitcoin
   - [ ] BTC Indexer
   - [ ] BTC Mempool
   - [ ] Ordinal Indexer
   - [ ] Rune Indexer
- [ ] API development
   - [ ] BTC
   - [ ] Ordinals
   - [ ] Rune
- [ ] UI development
   - [ ] Display assets
   - [ ] Send assets
   - [ ] Transactions history
   - [ ] SWAP: BTC <=> DOT: Implemented in issue: https://github.com/Koniverse/Playnation/issues/56
